baseURL = "https://hugo-basics.netlify.com"
languageCode = "en-us"
title = "Hugo Basics"
canonifyurls = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  copyrighthtml = "Copyright © 2019 Andler Develops. All Rights Reserved."
  sidebarrecentlimit = 5
  author = "AndlerRL"
  twitteruser = "AndlerRL"
  css = ["main.css"]
  js = ["main.js"]